### ISSUE TITLE
API should handle caching of results or not require caching

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#11]

**Comment by jonathancrabtree** [comment]
Can this issue be moved or closed? It appears to be a dashboard-api issue, not a dashboard issue. In addition, since deriva-py implements client-side caching by default I believe that by extension dashboard-api should do the same.

**Comment by jrchudy** [comment]
@jonathancrabtree it looks like we changed the dashboard pages to use the dashboard APIs instead of the cached JSON documents. If this issue is intended to be for dashboard-api as you suggested, we can move it.

If these changes have already been made in the dashboard-api repo, then we can just close this instead of moving it.

**Comment by jonathancrabtree** [comment]
The API handles result caching thanks to the built-in caching provided by the deriva-py layer. There is the separate question of whether it's sufficient, particularly for initial requests involving non-public catalogs, but I think that's probably covered by https://github.com/nih-cfde/dashboard-api/issues/13 and so I'm closing this case.
