### ISSUE TITLE
Clicking through and of the"X with Y" links in review page fails spectacularly

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#113]
I made a short video of "Files with Subject", but it happens with all of the "X with Y"

https://user-images.githubusercontent.com/1719360/139308123-878d3875-099a-43a9-8bf7-c1df23cc3d32.mov

**Comment by jrchudy** [comment]
This should be fixed with the next hourly update on dev. I will test there once it has been updated.

**Comment by jrchudy** [comment]
When calling the function (`var chaise_uri = get_chaise_uri(catalog_id, entity, data['RID']);`), the “RID” value is trying to be fetched from the returned data, but that RID value does not exist in the returned data. The returned data:
```
abbreviation: "MW"
biosample_count: 111093
complete_name: "UCSD Metabolomics Workbench"
datapackage_RID: "1B76"
description: "The Metabolomics Workbench is the NIH Common Fund's National ..."
file_count: 1840
id: "cfde_registry_dcc:test1"
last_updated: "2021-10-27T17:41:20.310101+00:00"
nid: 1
principal_investigators: []
project_count: 885
subject_count: 1377
toplevel_project_count: 885
url: "https://genome.ucsd.edu/"
```

The `RID` value that used to be present was replaced with `nid`. So changing the line mentioned above to pass `data['nid']` instead is part of the solution.

Each path defined in `dcc_review.js` to generate the facet blob from was ending in `RID` still, so changing that path to use `nid` instead fixed the issue with the queries showing "unsupported filters" on recordset page.

Another issue I found was that each url that is being generated has `@sort(RID)` appended to it. This is causing the deriva page to error as well since RID is not “sortable” in this instance. There’s no need to include this sort term, since deriva will choose the appropriate default sort criteria and append that to the url

**Comment by jrchudy** [comment]
Looks like _almost_ every link works on staging after the update. The 2nd projects link still does not work after the change I made :(

**Comment by jrchudy** [comment]
The one link I mentioned in my last comment is still broken. After some investigating, it looks like the generated facet blob is missing the "choice" value.

The difference between the 2 projects links for this review catalog on dev is shown below.
https://app-dev.nih-cfde.org/dcc_review.html?catalogId=106

First link on dcc_review page (total projects):
```
N4IghgdgJiBcDaoDOB7ArgJwMYFM6JAEsIAjdafEAYQDEARAURABoQAHDFAKxywBcA+sQEduvQVgAWhADZQBAMwDWOAJ4gAugF9modHzJoKCavSatRPfkIgjOVwWzAYcEQcrWadoYoePxTRhZ2e3EbOzFrPgxIJEI+QgA3HAEAWxxUkhwMRRV1bV0QfT8YE1ogi1DrYUsw6Nj4pJSZHDAobNzPApAIQhgNVikUQlwkSgBGL20gA
```
```
choices: ['1'],
source: Array(5)
0:
inbound: (2) ['CFDE', 'project_in_project_child_fkey']
[[Prototype]]: Object
1:
outbound: (2) ['CFDE', 'project_in_project_parent_fkey']
[[Prototype]]: Object
2:
inbound: (2) ['CFDE', 'project_in_project_transitive_member_fkey']
[[Prototype]]: Object
3:
outbound: (2) ['CFDE', 'project_in_project_transitive_leader_fkey']
[[Prototype]]: Object
4: "nid"
```

Second link under breakdown:
```
N4IghgdgJiBcDaoDOB7ArgJwMYFM6JAEsIAjdafEAYQDEARAURABoQAHDFAKxywBcA+sQEduvQVgAWhADZQBAMwDWOAJ4gAugF9modHzJoKCavSatRPfkIgjOVwWzAYcEQcrWadoYoePxTRhZ2e3EbOzFrPgxIJEI+QgA3HAEAWxxUkhwMRRV1bV0QfT8YE1ogi1DrYUsw6Nj4pJSZHDAobNzPApAIQhgNVikUQlwkSi9tIA
```
```
choices: ['']
source: Array(5)
0:
inbound: (2) ['CFDE', 'project_in_project_child_fkey']
[[Prototype]]: Object
1:
outbound: (2) ['CFDE', 'project_in_project_parent_fkey']
[[Prototype]]: Object
2:
inbound: (2) ['CFDE', 'project_in_project_transitive_member_fkey']
[[Prototype]]: Object
3:
outbound: (2) ['CFDE', 'project_in_project_transitive_leader_fkey']
[[Prototype]]: Object
4: "nid"
```

**Comment by jrchudy** [comment]
Other link that is broken is in the linked issue, closing this issue.
