### ISSUE TITLE
Hoverover text issues on dashboard

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#127]
technically this is two different issues. 

1. in the interactive bar plot, none of the DCC hoverover/'i's are working
![image](https://user-images.githubusercontent.com/1719360/160701853-5f759e6d-7e3e-4581-a35d-024e24ade798.png)

2. in the donut charts, in the slice hover overs, when the title has a hanging letter, it clashes with the description

![image](https://user-images.githubusercontent.com/1719360/160701804-4fe7832d-b4bd-4055-8721-1b54e5fdf04c.png)
![image](https://user-images.githubusercontent.com/1719360/160701828-0ca03aca-4794-44be-9a50-694a92f6aa75.png)

**Comment by jrchudy** [comment]
The hover 'i's appear to be working for me (I have to make sure that browser window is focused and I wait 2-3 seconds before it shows). 

I tested this on mac with chrome.

![image](https://user-images.githubusercontent.com/2932600/160916536-5ac41ab6-3e93-48e7-88aa-23d2db8d0423.png)

**Comment by ACharbonneau** [comment]
Today those hoverovers are working for me too! Yay for leaving it till it fixes itself :)

**Comment by mschor** [comment]
Hi Amanda, just wondering what browser and OS you were using. I can't reproduce the tooltip issue either. I'm glad it's now working for you. I'm working on the other issue here: donut chart tip spacing.

**Comment by ACharbonneau** [comment]
I am also on a mac with chrome. No idea why it stopped or suddenly started working. I did restart my computer overnight, so it might have been some weird cache thing

**Comment by mschor** [comment]
Ok, thanks for letting me know. I've fixed the donut chart spacing issue. I also found another issue with the donut charts while working on that. If you hover over the colorful square boxes that make up the legend, it highlights portions of the donut, but the tooltip was blank. That's fixed as well. It should go out to dev at 5:00. I'm not sure what triggers a deployment to staging. I'll tag it and see if it goes there; otherwise, I'll ping Mike D.
