### ISSUE TITLE
Change background color of exported PNG data preview graph to white

### ISSUE THREAD

**Issue by jessicalumian** [nih-cfde/dashboard#130]
This is regarding the data graph on the main page.

<img width="1577" alt="Screen Shot 2022-03-30 at 3 16 14 PM" src="https://user-images.githubusercontent.com/9140844/160940122-5b9ff796-4b4b-45c0-a449-8a3c6c61a268.png">

If the data preview graph is exported as a PNG, the image has a gray background, which is difficult to read.

<img width="1754" alt="Screen Shot 2022-03-30 at 3 18 58 PM" src="https://user-images.githubusercontent.com/9140844/160940446-ff0b54f0-5a7d-4d98-aaea-7a0847dd645d.png">

If the graph is exported as an SVG, it has a white background, which looks much better.
<img width="1725" alt="Screen Shot 2022-03-30 at 3 18 25 PM" src="https://user-images.githubusercontent.com/9140844/160940382-75f93b3a-03b0-4196-8f1b-3af43efd0b72.png">

Would it be possible to make the PNG export also have a white background?

Also, would it be possible to make the names on the X axis fully displayed? I understand space is limited on the webpage, but if an image is it seems like enough space could be given to display those labels.

**Comment by jrchudy** [comment]
From further investigation, this appears to be a combination of the PNG being exported with a transparent background and the computer display settings being in light vs dark theme. We should investigate if the image can be exported with a white background.

Macbook with "dark theme":
<img width="971" alt="image" src="https://user-images.githubusercontent.com/2932600/167200044-c0fa5999-a5d2-4f6d-8f14-09e61893fa31.png">

Macbook with "light theme":
<img width="954" alt="image" src="https://user-images.githubusercontent.com/2932600/167200209-80005613-9fc3-4144-87b1-3b3ae60c379b.png">

**Comment by jonathancrabtree** [comment]
The label adjustment component of the issue is now a separate issue, #136

**Comment by jonathancrabtree** [comment]
Please note that originally the PNG export had a transparent background and the SVG export had no background at all. The issue description says that the SVG had/has a white background, but this is not the case. For both PNG and SVG images different viewers will display a transparent or absent background in different ways (e.g., as white, black, grey, or checkered.)

So while the PNG export should now always display with a white background, there are viewers that may not render the SVG export's (lack of) background as white. For example, here is what the SVG graph looks like by default in the GNU Image Manipulation Program (GIMP):

![Screen Shot 2022-05-31 at 1 14 12 PM](https://user-images.githubusercontent.com/5394345/171235297-b1bd05c4-3737-4c75-aab0-f9ef627849aa.png)

However, I'd recommend leaving it this way because I think it's not uncommon practice to refrain from explicitly painting the background in SVG figures, assuming that white will be used. Since PNG is a bitmapped format the background has to be set to *something* and that's usually either transparent or white.

**Comment by raynamharris** [comment]
see https://github.com/nih-cfde/cfde-deriva/issues/363#issuecomment-1176696872
