### ISSUE TITLE
Exported PNG from firefox is blank

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#139]
I did some more debugging and was able to determine that this is happening for our PNGs downloaded using firefox. The PNG I downloaded with chrome shows fine in firefox and with mac preview. The PNG I downloaded with firefox does not show in chrome or with mac preview.

This was found during testing:
https://github.com/nih-cfde/cfde-deriva/issues/363#issuecomment-1176696872

**Comment by jonathancrabtree** [comment]
Confirmed that (on MacOS):

- SVG export works correctly on Firefox, Chrome, and Safari
- PNG export works on Safari and Chrome but generates a blank image on Firefox (and the PNG file size is significantly lower)

And also that:
- Dashboard package.json and package-lock.json require save-svg-as-png 1.4.17 and this is the most recent version available; see [https://github.com/exupero/saveSvgAsPng/tags ](https://github.com/exupero/saveSvgAsPng/tags)

One possibility is that the method used to export a different version of the chart than the one that's displayed (i.e., in order to display the full-length labels, as per #136) is not working in Firefox for some reason.

**Comment by jonathancrabtree** [comment]
This should be fixed now. It was indeed a side effect of the code used to export a different version of the chart than the one that's displayed. The original code added an invisible SVG element to the end of the page and rendered the chart to be exported into that SVG element. In both Chrome and Safari this technique worked just fine, but in Firefox (and only for the PNG export) the export code actually paid attention to the fact that it was invisible and rendered it accordingly...

The code now hides the new SVG element beneath a 1x1 pixel div with hidden overflow, which appears to work in Chrome, Firefox, and Safari for both PNG and SVG export. My testing procedure was as follows:

1. Load main dashboard page.
2. Click on "DOWNLOAD"
3. Choose "Export as SVG" and check the output
5. Choose "Export as PNG" and check the output
6. Close the export dialog box
7. Change x-axis from "Data Type" to "Disease". Note that this results in a very wide plot.
8. Repeat steps 2-6

I also checked while doing this that the underlying page didn't change noticeably (i.e., there was no second copy of the chart suddenly appearing at the bottom of the page during export.)

**Comment by jessicalumian** [comment]
Just downloaded the PNG on app-dev and it looks great!


<img width="1504" alt="Screen Shot 2022-07-13 at 4 04 11 PM" src="https://user-images.githubusercontent.com/9140844/178851621-6cfad843-e3d5-43e4-8b4e-dd55804b3e4c.png">

**Comment by jrchudy** [comment]
Also verified this is working now. Closing this issue.
