### ISSUE TITLE
Rotating Carousel of Highlighted Videos

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#141]
On the bottom of the homepage, in the same column as funding, we want to add a widget that scrolls through different videos about the CFDE. The videos are some of the videos that are present under the "User Help" -> "Video Overviews" link in the navbar. We should use the first 10 videos under the [appendix](https://github.com/nih-cfde/2022-CoC-Videos/blob/main/docs/appendix.md) and the NIH video from the top of the ["Video Overviews" page](https://nih-cfde.github.io/2022-CoC-Videos/).

- NIH video: https://www.youtube.com/watch?v=cWZPTjG5_Us
   - Learn how the Common Fund Data Ecosystem is developing an online portal that will allow researchers to access and work across multiple NIH Common Fund program data sets within a digital cloud environment.

1. Portal Overview: https://www.youtube.com/watch?v=aN8n2I1pROk
   - A overview of the portal for navigation of cross-project data using a flexible metadata standard for describing experimental resources in biomedicine and related fields.
2. Data Submission Tools and Processes: https://www.youtube.com/watch?v=i0qWaa8chNQ
   - This video covers the process of submitting data to the Common Fund Data Ecosystem portal.
3. C2M2 Compatibility Test: https://www.youtube.com/watch?v=QST9HtwzwjE
   - The CFDE C2M2 FAIR Datapackage Assessment Appyter enables DCCs to test the FAIRness of their C2M2 compatible data packages before uploading to the CFDE portal for ingestion.
4. Content Registry and Knowledge Base: https://www.youtube.com/watch?v=3ePYK1YvwQU
   - The Knowledge Base in the Common Fund Data Ecosystem's search portal hosts additional information on pages.
5. A re-usable Solution for Knowledge Management C2M2: https://www.youtube.com/watch?v=bNoZ47QoRWc
   - An overview of the Knowledge Management C2M2 model for finding biomedical data using the Common Fund Data Ecosystem portal.
6. Knowledge Graph: https://www.youtube.com/watch?v=ijrivk3G9-Y
   - The ability to access, via a human interface or an API, a vast, semantically-coherent knowledge graph integrated from data and relationships generated from different Common Fund projects.
7. Genes and Variants: https://www.youtube.com/watch?v=3eIBdcNngrA
   - Researchers can use the Gene-Centric Appyter to query a gene or variant of interest across all Common Fund Data Ecosystem groups for information returned in a summary report.
8. Drugs and Birth Defects: https://www.youtube.com/watch?v=w7IKp4wQ1VM
   - This video demonstrates ways for researchers to easily assemble collated and organized information on genes of interest using the ReproTox Knowledge Graph.
9. Cancer Research: https://www.youtube.com/watch?v=Z1hybV-V6ck
   - This video describes a precision therapy use case focused on pediatric cancer using RNA-seq data from Kids First and GTEx.
10. Assessment of Genetic Variants in Human Disease: https://www.youtube.com/watch?v=_6KQZ6eUHAE
    - This video illustrates how CFDE resources are used to analyze whole genome sequencing data for the study of regulatory non-coding variants in congenital heart disease.
   
There's an example of a simple carousel implemented for the training website (https://training.nih-cfde.org/en/latest/) and the code for this implementation can be found in the `carousel` branch of the training repo (https://github.com/nih-cfde/training-and-engagement/blob/carrousel/custom/overrides/home.html)

Alternative suggestion:
This could be a simple widget that links to a playlist of videos that can be managed outside of the code base.

**Comment by jessicalumian** [comment]
The proper links and text have been added to the comment above.

**Comment by jonathancrabtree** [comment]
Homepage before adding anything new:

![Screen Shot 2022-09-19 at 11 00 00 AM](https://user-images.githubusercontent.com/5394345/191326622-22c2736e-12d9-41c0-b08e-5d7d351becdb.png)

Initial attempt with the first 3-4 slides and dark/black background:

![Screen Shot 2022-09-20 at 8 52 41 AM](https://user-images.githubusercontent.com/5394345/191326811-199dbbe6-eaa0-4f37-85a3-f72386d5a2b7.png)

Revised version with white background and all slides (the whitespace on either side of the YouTube video isn't fixed, it depends on the overall window width):

![Screen Shot 2022-09-20 at 1 34 48 PM](https://user-images.githubusercontent.com/5394345/191326977-d37d53bd-6623-4b5f-9f3c-3d4b9e2547c3.png)

**Comment by jonathancrabtree** [comment]
This is now available for review on app-dev:

![Screen Shot 2022-09-20 at 2 09 30 PM](https://user-images.githubusercontent.com/5394345/191332637-f3862bca-2db2-44e1-97d0-f2e2baa2a5f0.png)

A couple of notes:

- I changed the title of the first video from "NIH video" to "CFDE Overview" because the former seemed a bit generic and the latter more closely matches the 2nd video ("Portal Overview")
- Changed "A overview" to "An overview" in the description of the 2nd video (labeled "1." in the list above)
- The carousel will auto-rotate, but only after the user has made a slide transition manually.
- The auto-rotation will pause when the mouse is hovered over the panel.
- The slide transitions are consistent with the indicated order.
- I don't think a title was specified for the panel, so I went with "Highlighted videos", thinking that "Highlighted overview videos" or "Selected overview videos" might be a bit verbose.

**Comment by jessicalumian** [comment]
This looks great on app-dev! I agree with all of your notes too.

**Comment by jonathancrabtree** [comment]
As discussed at last Friday's meeting, I checked that the height of the Social media box is fixed (it is, with the Twitter widget's `data-height` set to 400) and then made the previous alternate layout (with the videos in the middle) the new default. See [here](https://app-dev.nih-cfde.org/) (requires CFDE VPN login.)

Note also that there seems to be a slight issue with the auto-deployment code, because although the file index-alt.html is no longer present on the master branch, it is still present on the app-dev web server.
