### ISSUE TITLE
Fix link in dcc_review.html page

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#47]
Just under the DCC name there is a link. 
![image](https://user-images.githubusercontent.com/1719360/107076842-01ff0400-67ba-11eb-8437-50f50cbe6a8c.png)

This is supposed to go to the chaise recordset for the submission being viewed, as it does in the current public site demo https://app.nih-cfde.org/dcc_review.html 

But in dev currently it seems to have reverted to a static link to the DCCs website.

**Comment by jonathancrabtree** [comment]
This was probably my fault. I forget my exact thought process, but the (then) static link into Chaise looked like an error and I think I just assumed the intent was to link all the way back to the source DCC. In my defense I will point out that the link into Chaise for "More at"  is an exact duplicate of one of those now available in the "Data Review" box. I guess the idea is that since the summary chart is showing file counts it makes sense to link to all Files for more information (rather than to all subjects, or all biosamples, or all projects)? Although that may still be confusing because the chart is only showing counts for "Files with Biosample", so the total counts are unlikely to match.

**Comment by ACharbonneau** [comment]
That's a reasonable point about the data review box. In the demo those weren't links, so now it might be redundant. My main concern is minimizing the number of links that leave the website, and since these pages are only visible by DCC staff, it seems really unnecessary to tell them where their own website is. 

Since there's so many links to the chaise info, maybe we really want that link to go to the 'submitted datapackage' page? like this one:https://app-dev.nih-cfde.org/chaise/record/#registry/CFDE:datapackage/RID=4HE

**Comment by jonathancrabtree** [comment]
That looks like a useful link to have and it's not there already. How would you feel about also changing "More at:" to "Submitted datapackage at:" or "Submitted datapackage:" or something along those lines? 

It's true that the DCC doesn't need a link to their own website, although that particular link isn't exactly static, it's being pulled from the database and--by extension--the submitted datapackage, so on the off chance that the link points to something other than their website, that's actually an error in the submission that should be flagged and corrected before the catalog is approved. (However, none of that it is at all clear from how the link is currently being presented and it probably shows up elsewhere i.e., in Chaise, if someone really wanted to check it.)

**Comment by ACharbonneau** [comment]
> That looks like a useful link to have and it's not there already. How would you feel about also changing "More at:" to "Submitted datapackage at:" or "Submitted datapackage:" or something along those lines?

I like it. Let's do that.

**Comment by jonathancrabtree** [comment]
Sounds good. This should be trivial, but it's going to take me a bit of work to get set up with the code and Globus permissions to be able to view the auth-restricted pages in my laptop dev environment so that I can actually test before committing...

**Comment by jonathancrabtree** [comment]
Getting there. Permissions issues were resolved on Friday and I've got a mostly-working local install of Chaise and ERMRest.

**Comment by jonathancrabtree** [comment]
Working on this. Need to make a small modification to the dashboard-api so that the /dcc/<dccName> endpoint will return the RID needed to construct the data package URL.

**Comment by jonathancrabtree** [comment]
This may be a slightly larger can of worms than I'd anticipated; it looks like the dashboard-api will need to query the registry database to find the datapackage RID that corresponds to a given catalog id. @ACharbonneau, let me know if you think this is not the case.

**Comment by ACharbonneau** [comment]
I expect there is some amount of having to figure out which catalog it is, I don't know the infrastructure well enough to know that's the right way to do it, but it sounds plausible to me. The page does have the summary stats from the catalog, would it be easier to move the link down into the "Data Review" section and make it part of the query that's presumably already happening there?

**Comment by jonathancrabtree** [comment]
Still working on the correct fix for this. Moving the location of the link doesn't help because dashboard-api does not currently do _any_ queries against the registry catalog - it was developed before that was a thing. I've committed a change that's slightly better than what we had before - instead of linking to the DCC's public web site, the link now says "Submitted datapackages:" and it links back to the list of _all_ datapackages (that the current user can see.) If there's only 1 submitted datapackage then we're good, otherwise the user is going to have to search for the right one. Once I get the query for the datapackage RID in there I'll fix this so it links to just that one datapackage.

**Comment by ACharbonneau** [comment]
Actually, just that link back sounds like a reasonable thing to do. I noticed in another issue that theres no easy way to get back to the registry: https://github.com/nih-cfde/cfde-deriva/issues/151 and it sounds like this would help with that problem

**Comment by jonathancrabtree** [comment]
A fix for this will be in dashboard and dashboard-api RC2:

![Screen Shot 2021-03-01 at 5 07 11 PM](https://user-images.githubusercontent.com/5394345/109565572-a8d07a80-7ab0-11eb-8e44-9c7fce9825d1.png)

**Comment by jonathancrabtree** [comment]
@ACharbonneau, this is live on staging.

**Comment by ACharbonneau** [comment]
looks right to me
