### ISSUE TITLE
File counts seem wrong

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#70]
In this users summary charts: https://app.nih-cfde.org/dcc_review.html?catalogId=13

if you set the chart to x-axis:`species`, y-axis:`file`, stackby:`anatomy` it plots more than the total number of files:

![image](https://user-images.githubusercontent.com/1719360/110675242-abae2800-81a0-11eb-89ff-6bc9c7493d3f.png)

270,797 + 2,881 =273,678 not 273,146

**Comment by jonathancrabtree** [comment]
@ACharbonneau this is precisely the issue I raised when the decision was originally made to report these summary counts in this fashion, probably back in Epic 1. It is absolutely the case that these graphs are reporting totals that exceed the known number of Files/Subjects/etc. and in an earlier version of the summary tables the problem was actually worse (i.e., the total number of reported Files could exceed the actual count by an even larger margin.) It's no surprise that users are confused by this behavior, so perhaps we need to revisit those earlier discussions and come up with a better long-term solution. The crux of the problem is, I think, that the graphs aren't really showing counts of files (or subjects or biosamples or whatever), they're showing counts of _links_ to files (in this case links from species to files.) And if a species can be linked to a particular file by 2 paths in the data model, that gets reported as 2 "files", not one file.

**Comment by ACharbonneau** [comment]
Agree, let's revisit. Is it easy to share the full mapping of what the table is actually doing to generate numbers right now?

**Comment by jonathancrabtree** [comment]
Do you mean the table or the graph? I believe the numbers in the table ("Data Breakdown") are correct and those are generated by the dcc_linkscount method in the following file from dashboard-api. It uses the Python API to query DERIVA directly (i.e., without using the StatsQuery table and the associated summary tables in DERIVA) precisely because this was the only way to obtain accurate counts (it is, however, much slower than using the summary tables):

https://github.com/nih-cfde/dashboard-api/blob/master/dashboard/dashboard_api.py

The graph, on the other hand, is populated using data from custom-built summary tables in DERIVA (via the StatsQuery module in cfde-deriva) and I don't know where the code to _generate_ those tables resides; this may be a question that @karlcz can answer. In any case, I believe the summary tables behind the StatsQuery module are ultimately the source of the summary counts we're talking about. Not sure if this gives you a "full mapping" but that's the extent of my knowledge!

**Comment by ACharbonneau** [comment]
That's helpful. And based on that, by full mapping, I think I likely meant something like "can you tell me the StatsQuery queries that build the summary tables you're getting counts from". I want to try to understand how the queries get unexpected answers, so what path(s) it takes from table to table to build a query.

**Comment by jonathancrabtree** [comment]
Karl and Arthur explained this in detailed technical terms a while back but I think the fundamental problem is that the various database entities (i.e., files, subjects, biosamples, data types, anatomy terms) aren't all necessarily linked in a 1-1 fashion. This is a contrived example, but consider what would happen if you had a single file with expression data from two body sites, say arm and leg. If you plotted a chart with anatomy on the x-axis then that one file would be counted both in the bar for "leg" and also in the one for "arm." The per-bar counts could be accurate, but when you add them up you will still get something more than the maximum number of files.

From what Arthur and Karl were saying I think that what's actually going on in our current database is a little more complex (plus you may have some additional count inflation introduced by the summary process itself) but the point is that there may be 1-many or many-1 relationships between the things we are trying to count and so long as that is true we can't guarantee that the sums of the individual bars in our graphs will add up exactly to the total number of files/subjects/biosamples/etc.
