### ISSUE TITLE
Option (or automatic) scaling of plots

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#71]
Can we have the plots in the dashboard change how they present the axis scales when the data warrants?  

For instance, it would be great if the plot had an exponential scale for the y-axis so that the smaller bars were visible:

![Screen Shot 2021-03-09 at 12 17 07 PM](https://user-images.githubusercontent.com/5394345/110511970-c914c080-80d2-11eb-867c-1d97d32924ae.png)

Another suggestion would to be able to switch to percentages so the bars would get all the same height and make it easier to see categories

https://github.com/nih-cfde/published-documentation/discussions/195

**Comment by jonathancrabtree** [comment]
I've made some progress on this. One issue that came up was the question of how to sort the individual bars within each stacked bar of the graph. In the current implementation the "Stack by" categories are sorted _globally_ based on the total number of subjects/files/etc., regardless of x-axis category. That global order is then used across all x-axis categories. For example, in the following graph the "other" category has the largest total (when added across all assays on the x-axis). That's why it's shown at the bottom of the 3rd bar ("small mRNA sequencing assay") even though the next category up (cardiovascular assay) has a higher file count. It's not clear this is the best approach, but that's how the categories are sorted at the moment:

![Screen Shot 2021-03-29 at 2 09 00 PM](https://user-images.githubusercontent.com/5394345/112880385-5f1b8580-9098-11eb-8e14-4f87fb00b47d.png)

Alternatively, the categories could be sorted for each bar/x-axis category independently, as shown here. Now the anatomy term with the highest count (within each stacked bar) is always at the bottom, which I believe is typical in a stacked bar plot (i.e., the segments/pieces are sorted from largest to smallest as you move up each stack):

![Screen Shot 2021-03-29 at 2 05 14 PM](https://user-images.githubusercontent.com/5394345/112880403-6478d000-9098-11eb-872e-ce42a656d852.png)

When we switch to a logarithmic scale, however, this creates a problem for the smaller categories, particularly those which were already too small or almost too small to see.  If we leave them at the top of each stacked bar it makes them even smaller due to the logarithmic scale. The logical thing to do for a log scale stacked bar plot is to put the smallest segments at the bottom, where they are most visible. Of course the downside is that it's visually misleading and it makes it harder to glance at the graph and see how big the largest segment is in each bar:

![Screen Shot 2021-03-29 at 2 05 25 PM](https://user-images.githubusercontent.com/5394345/112880421-6b074780-9098-11eb-8201-b40ac70330cf.png)

Additionally, if we allow the user to select the scale, as shown here, we have the undesirable property that the order switches every time they change it.

**Comment by jonathancrabtree** [comment]
The more I think about this the more it seems like a logarithmic scale on a stacked bar graph is an inherently crazy thing: the whole point of it is to be able to see the relative contributions of the various components and with a nonlinear scale that's well nigh impossible, regardless of how the blocks are sorted. When I return to working on this I'll probably add Percentage as an option and then we can decide during testing/review which options to keep.

**Comment by jrchudy** [comment]
Closing this issue since we don't plan on adding a control for changing the scale of the bar plot.

We have discussed Upset plots as an alternative to the current bar plot to display the data.
https://acharbonneau.github.io/upset/

**Comment by jonathancrabtree** [comment]
Completing #144 allowed this to be implemented. See #144 for details.
