### ISSUE TITLE
Update navbar links

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#91]
### Update the navbar to align with the changes outlined in the `2021_May_Homepage1.pdf` in the [UX folder](https://drive.google.com/drive/u/1/folders/1crbuUEujulc9Pze9zdDFH_6CToUhKUHu).

Top Level options:
![image](https://user-images.githubusercontent.com/2932600/129822066-2d8ba6cb-0da9-4fc3-85eb-0015f3b143fa.png)

Data Browser:
![image](https://user-images.githubusercontent.com/2932600/129822113-6705463f-d517-447e-9254-fe2a8966d733.png)

For Submitters:
![image](https://user-images.githubusercontent.com/2932600/129822157-e37dbf29-ed66-4358-bda6-7632569791bf.png)

User Help:
![image](https://user-images.githubusercontent.com/2932600/129822094-c682116f-c7e1-4048-93cf-2ea7a077e14c.png)

### Changes outlined in the 2021_May_Summary.pdf in the UX folder.
With Review ACL:
![image](https://user-images.githubusercontent.com/2932600/129822265-87963e80-15d6-48cd-937e-13a3de353900.png)

**Comment by jrchudy** [comment]
@ACharbonneau I was working through this issue today and noticed that some of the links are new that we didn't have before. Could you clarify where each of the following menu options should go:
 - Under "For Submitters"
   - "QuickStart Guide" -
   - "cfde-submit Docs" -
      - should this be the text case for this option (`cfde-submit Docs`)?
   - "C2M2 Docs" -
   - "My Submissions" - "/chaise/recordset/#registry/CFDE:datapackage"
      - should we show `(requires login)`?
      - do we disable the option when user is not logged in (and the user doesn't have the proper review status)? should disabling take place of `(requires login)`?
 - Under "User Help"
    - "Portal User Guide" - "https://cfde-published-documentation.readthedocs-hosted.com/en/latest/about/portalguide/"
    - "Cohort Building Tutorial" -
    - "About the CFDE" - "https://www.nih-cfde.org/"
 - Under "Review Options"
    - "Submission: <hash>" - no url per [amanda's notes doc](https://docs.google.com/document/d/1tYtBXL3HmxSbyA8lVwCvXQKQI6xssoL3pur65RyRxoY/edit#)
    - "View Summary Page - "/dcc_review.html?catalogId=%s" % self.catalog.catalog_id
    - "Browse This Datapackage" - "/chaise/record/#registry/CFDE:datapackage/RID=<rid-value>"
    - "Approve This Datapackage" - "/chaise/recordedit/#registry/CFDE:datapackage/RID=<rid-value>"
       - same questions from above for `(requires login)`
          - should we show `(requires approver status)`?
          - do we disable the option when the user doesn't have the proper approver status? should disabling take place of `(requires approver status)`?
          - I'm actually not sure if we have access to the checking the approver status (whether it's just a globus group or it requires row level acls too). Maybe @karlcz would know.
    - "View My Submissions" - "/chaise/recordset/#registry/CFDE:datapackage"

**Comment by karlcz** [comment]
Please note that we have three different navbars constructed by cfde-deriva:
1. The common one that is used in the default navbar for static site (I think?) and the release catalog "1"
2. One customized for the registry. This is what you see when looking at the list of submissions etc.
3. One customized for a submission. This is what you see when you browse to a review catalog or dcc_review charts page.

## submission

It drops the standard items:
- Dashboard
- Data Review

and appends instead:
- In-Review Submission

I see this is revised in this new design with the Review Options menu.

But, we're going to have to change the code where it modiies the base navbar, because it uses positional coordinates which are no longer accurate due to the other changes above.
- it applies a fixup to the Browse All Data entry assumed to be in position 0, now Data Browser in position 1
- the dashboard and data review links are already dropped, so we need to stop pruning the end of the list and only append the new menu instead

## registry

 It also drops:
 -  Dashboard
 -  Data Review

but appends instead:
- Submission System

Just to confirm, the design keeps this Submssion System menu unchanged?

We also need to apply the same corrections as in the submission case, for any manipulation of the Data Browser menu as well as the pruning of the inherited navbar config.

**Comment by jrchudy** [comment]
The linked PR has been merged. Changing this to Review/QA.
